\c smsc_db;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO smsc_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON SEQUENCES TO smsc_user;

GRANT ALL ON SCHEMA public TO smsc_user;
